Added hijack
Som-Energia/somenergia-solarprosumers pull request #16
Opened 2021-07-30 06:54 UTC by BenjiRS94

Integrated Hijack for administration management and reduce time resolve of issues

2021-08-10 07:12 UTC, JoanaFigueira approved these changes

2021-08-12 10:07 UTC, juan-pe requested changes
Only one change, add hijack to requirements ;)

2021-08-13 07:38 UTC, BenjiRS94 commented
`django-hijack` and `django-hijack-admin` are already added into `requirements.txt`, do you need any more?

2021-08-13 07:41 UTC, juan-pe approved these changes
perfect!

2021-08-16 08:31 UTC, merged